"""Add prompt field to Dashboard

Revision ID: d28ac101eb4f
Revises: 52a4f81c3f49
Create Date: 2025-05-16 19:54:33.610858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28ac101eb4f'
down_revision = '52a4f81c3f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.Text(), nullable=True))
        batch_op.drop_column('gemini_analysis_text')
        batch_op.drop_column('last_analysis_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_analysis_timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('gemini_analysis_text', sa.TEXT(), nullable=True))
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###
